-- MySQL Script generated by MySQL Workbench
-- Mon Oct  5 16:46:40 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`permiso` (
  `idpermiso` INT NOT NULL AUTO_INCREMENT,
  `denominacion` VARCHAR(45) NOT NULL DEFAULT '-',
  `descripcion` VARCHAR(200) NULL DEFAULT '-',
  PRIMARY KEY (`idpermiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `IDrol` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `DNI` VARCHAR(10) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `correo_UNIQUE` ON `mydb`.`persona` (`correo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sala` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `capacidad` INT NOT NULL,
  `habilitada` TINYINT NOT NULL,
  `precio_x_hora` DECIMAL NOT NULL,
  PRIMARY KEY (`numero`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `mydb`.`sala` (`nombre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `nro` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_finalizacion` TIME NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `precio_alquiler_sala` DECIMAL NOT NULL,
  `total_reserva_inventario` DECIMAL NOT NULL,
  `persona_DNI` VARCHAR(10) NOT NULL,
  `sala_numero` INT NOT NULL,
  PRIMARY KEY (`nro`, `persona_DNI`, `sala_numero`),
  CONSTRAINT `fk_reserva_persona1`
    FOREIGN KEY (`persona_DNI`)
    REFERENCES `mydb`.`persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_sala1`
    FOREIGN KEY (`sala_numero`)
    REFERENCES `mydb`.`sala` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reserva_persona1_idx` ON `mydb`.`reserva` (`persona_DNI` ASC) VISIBLE;

CREATE INDEX `fk_reserva_sala1_idx` ON `mydb`.`reserva` (`sala_numero` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(200) NOT NULL,
  `categoria_idcategoria_padre` INT NOT NULL,
  PRIMARY KEY (`idcategoria`, `categoria_idcategoria_padre`),
  CONSTRAINT `fk_categoria_categoria1`
    FOREIGN KEY (`categoria_idcategoria_padre`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_categoria_categoria1_idx` ON `mydb`.`categoria` (`categoria_idcategoria_padre` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fabricante` (
  `idfabricante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idfabricante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item_inventario` (
  `iditem_inventario` VARCHAR(10) NOT NULL,
  `stock` INT NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `costo_alquiler` DECIMAL NOT NULL,
  `categoria_idcategoria` INT NOT NULL,
  `fabricante_idfabricante` INT NOT NULL,
  PRIMARY KEY (`iditem_inventario`, `categoria_idcategoria`, `fabricante_idfabricante`),
  CONSTRAINT `fk_item_inventario_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `mydb`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_inventario_fabricante1`
    FOREIGN KEY (`fabricante_idfabricante`)
    REFERENCES `mydb`.`fabricante` (`idfabricante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_item_inventario_categoria1_idx` ON `mydb`.`item_inventario` (`categoria_idcategoria` ASC) VISIBLE;

CREATE INDEX `fk_item_inventario_fabricante1_idx` ON `mydb`.`item_inventario` (`fabricante_idfabricante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleado` (
  `persona_DNI` VARCHAR(10) NOT NULL,
  `legajo` INT NOT NULL AUTO_INCREMENT,
  `contraseña` VARCHAR(50) NOT NULL,
  `rol_IDrol` INT NOT NULL,
  `persona_DNI1` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`persona_DNI`, `persona_DNI1`),
  CONSTRAINT `fk_empleado_rol1`
    FOREIGN KEY (`rol_IDrol`)
    REFERENCES `mydb`.`rol` (`IDrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_persona1`
    FOREIGN KEY (`persona_DNI1`)
    REFERENCES `mydb`.`persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `legajo_UNIQUE` ON `mydb`.`empleado` (`legajo` ASC) VISIBLE;

CREATE INDEX `fk_empleado_rol1_idx` ON `mydb`.`empleado` (`rol_IDrol` ASC) VISIBLE;

CREATE INDEX `fk_empleado_persona1_idx` ON `mydb`.`empleado` (`persona_DNI1` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`cableado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cableado` (
  `metros_de_largo` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instrumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instrumento` (
  `afinacion` VARCHAR(50) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipo_de_audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipo_de_audio` (
  `potencia` INT NOT NULL,
  `canales` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pago` (
  `idpago` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `monto` DECIMAL NOT NULL,
  `medio_de_pago` VARCHAR(45) NOT NULL,
  `reserva_nro` INT NOT NULL,
  PRIMARY KEY (`idpago`, `reserva_nro`),
  CONSTRAINT `fk_pago_reserva1`
    FOREIGN KEY (`reserva_nro`)
    REFERENCES `mydb`.`reserva` (`nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pago_reserva1_idx` ON `mydb`.`pago` (`reserva_nro` ASC) VISIBLE;

CREATE UNIQUE INDEX `reserva_nro_UNIQUE` ON `mydb`.`pago` (`reserva_nro` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`indica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`indica` (
  `nro` INT NOT NULL AUTO_INCREMENT,
  `rol_IDrol` INT NOT NULL,
  `permiso_idpermiso` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`nro`, `rol_IDrol`, `permiso_idpermiso`),
  CONSTRAINT `fk_rol_has_permiso_rol`
    FOREIGN KEY (`rol_IDrol`)
    REFERENCES `mydb`.`rol` (`IDrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_has_permiso_permiso1`
    FOREIGN KEY (`permiso_idpermiso`)
    REFERENCES `mydb`.`permiso` (`idpermiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_rol_has_permiso_permiso1_idx` ON `mydb`.`indica` (`permiso_idpermiso` ASC) VISIBLE;

CREATE INDEX `fk_rol_has_permiso_rol_idx` ON `mydb`.`indica` (`rol_IDrol` ASC) VISIBLE;

CREATE UNIQUE INDEX `rol_IDrol_UNIQUE` ON `mydb`.`indica` (`rol_IDrol` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`aparta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aparta` (
  `nro` INT NOT NULL,
  `reserva_nro` INT NOT NULL,
  `item_inventario_iditem_inventario` VARCHAR(10) NOT NULL,
  `precio_unit` DECIMAL NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`reserva_nro`, `item_inventario_iditem_inventario`, `nro`),
  CONSTRAINT `fk_reserva_has_item_inventario_reserva1`
    FOREIGN KEY (`reserva_nro`)
    REFERENCES `mydb`.`reserva` (`nro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_has_item_inventario_item_inventario1`
    FOREIGN KEY (`item_inventario_iditem_inventario`)
    REFERENCES `mydb`.`item_inventario` (`iditem_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reserva_has_item_inventario_item_inventario1_idx` ON `mydb`.`aparta` (`item_inventario_iditem_inventario` ASC) VISIBLE;

CREATE INDEX `fk_reserva_has_item_inventario_reserva1_idx` ON `mydb`.`aparta` (`reserva_nro` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`control_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`control_inventario` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `empleado_persona_DNI` VARCHAR(10) NOT NULL,
  `item_inventario_iditem_inventario` VARCHAR(10) NOT NULL,
  `fecha` DATE NULL,
  `observacion` VARCHAR(200) NULL,
  PRIMARY KEY (`numero`, `empleado_persona_DNI`, `item_inventario_iditem_inventario`),
  CONSTRAINT `fk_empleado_has_item_inventario_empleado1`
    FOREIGN KEY (`empleado_persona_DNI`)
    REFERENCES `mydb`.`empleado` (`persona_DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_has_item_inventario_item_inventario1`
    FOREIGN KEY (`item_inventario_iditem_inventario`)
    REFERENCES `mydb`.`item_inventario` (`iditem_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_empleado_has_item_inventario_item_inventario1_idx` ON `mydb`.`control_inventario` (`item_inventario_iditem_inventario` ASC) VISIBLE;

CREATE INDEX `fk_empleado_has_item_inventario_empleado1_idx` ON `mydb`.`control_inventario` (`empleado_persona_DNI` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
